# Generated by Django 6.0.7 on 2026-07-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='vivencia.turmas')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Presente'), ('F', 'Falta')], max_length=1, null=True)),
                ('dia_ponto', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('observacao_presenca', models.TextField(blank=True, null=True)),
                ('atividade_diaria', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='vivencia.aluno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aluno', 'dia_ponto'), name='unique_presenca_por_dia')],
            },
        ),
    ]
