# Generated by Django 6.0.7 on 2026-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Foto_Aluno',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
