# Generated by Django 6.0.7 on 2026-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0002_aluno_foto_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Foto_Aluno',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/'),
        ),
    ]
