# Generated by Django 6.0.7 on 2026-07-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0003_alter_aluno_foto_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Foto_Aluno',
            new_name='foto',
        ),
    ]
