# Generated by Django 6.0.7 on 2026-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0004_rename_foto_aluno_aluno_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio_diario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
