# Generated by Django 6.0.7 on 2026-08-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0005_relatorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaVivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_da_empresa', models.CharField(max_length=100)),
                ('numero_responsavel', models.CharField(max_length=20)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_local', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('raio_permitido', models.PositiveIntegerField(default=250, help_text='Raio em metros')),
            ],
        ),
        migrations.AddField(
            model_name='presenca',
            name='latitude_registrada',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='longitude_registrada',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='relatorios',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='dia_ponto',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='status',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='aluno',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vivencia.empresavivencia'),
        ),
        migrations.AddField(
            model_name='empresavivencia',
            name='local_da_empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vivencia.localizacao'),
        ),
    ]
