# Generated by Django 6.0.7 on 2026-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0006_empresavivencia_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], max_length=5, null=True),
        ),
    ]
