# Generated by Django 6.0.7 on 2026-08-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivencia', '0007_aluno_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vivencia.turnos'),
        ),
    ]
